### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by pustule** [thefinn93/cjdnsmap#2]
what is the memory requirement?  I tried to run it on a vm with 1G RAM and on a physical server with 4G RAM.

On both, I got:

fdp: graph is too large for cairo-renderer bitmaps. Scaling by 0.491657 to fit
fdp: failure to create cairo surface: out of memory

**Comment by thefinn93** [comment]
Shit i have no idea. File this with [gerard-](https://github.com/gerard-/cjdnsmap) who wrote most of the code (I just keep things up to date with the cjdns admin and such
